blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://lana-software.github.io/Lana-App/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://lana-software.github.io/Lana-App/
    about: Please report security vulnerabilities here.