blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://lana-software.github.io/Lana-App/
    about: Please ask and answer questions here.
  - name: Security Bug Bounty
    url: https://lana-software.github.io/Lana-App/
    about: Please report security vulnerabilities here.