name: Test and Deploy (si tubiera) 
run-name: ${{ github.actor }} La esta cagando

on:
  push:
    branches: 
      - main

jobs:
  test-my-eggs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
